CREATE DATABASE if NOT EXISTS Ngdule ;
USE Ngdule;
# 首先要把用户模型设计好
CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL ,
  password VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS counter_competitor (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS counter_judger (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE `vote` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uid` varchar(30) CHARACTER SET utf8 NOT NULL,
  `cid` varchar(30) CHARACTER SET utf8 NOT NULL,
  `score` int(11) NOT NULL,
  `type` varchar(30) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
